site_name: Datajob
repo_name: Datajob on GitHub
repo_url: https://github.com/vincentclaes/datajob

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: amber

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "restructured-text"
