site_name: Datajob
repo_name: Datajob on GitHub
repo_url: https://github.com/vincentclaes/datajob

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: amber

markdown_extensions:
  - toc:
      toc_depth: 2
#      slugify: !!python/name:pymdownx.slugs.uslugify_cased
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "restructured-text"
          rendering:
            heading_level: 3
