name: docs
on: [push]
#  push:
#    branches:
#      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocstrings
      - run: ls -la
      - run: pwd
      - run: mkdocs gh-deploy --force
